@host = http://localhost
@port = 8080
@baseUrl = /products
@url = {{host}}:{{port}}{{baseUrl}}
@headerContentTypeJson = Content-Type: application/json

### find all
GET {{url}}
{{headerContentTypeJson}}
